config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get  'help',  to: 'static_pages#help'
  get  'about', to: 'static_pages#about'
  get  'shops', to: 'static_pages#shops'
  get  'signup', to: 'users#new'
  get  'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :reviews, only: %i[new edit create update destroy show]
  resources :shop_foods, only: %i[index show]
  resources :likes, only: %i[create destroy]
  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :shops, only: %i[index show]
      resources :foods, only: %i[index]
      resources :areas, only: %i[index]
    end
  end
end

app/models/review_form.rb
# frozen_string_literal: true

class ReviewForm
  include ActiveModel::Model
  include HotpepperApi
  extend CarrierWave::Mount
  attr_accessor :review_id, :user_id, :food_id, :content, :title, :shop_id,
                :rate

  mount_uploader :picture, PictureUploader

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :rate, numericality: { greater_than_or_equal_to: 1,
                                   less_than_or_equal_to: 5,
                                   message: 'を選択してください' }
  validates :food_id, presence: { message: 'を選択してください' }
  validates :shop_id, presence: { message: 'を選択してください' }
  validates :content, presence: true, length: { maximum: 400 }

  delegate :persisted?, to: :review

  def initialize(attributes = nil, review: Review.new)
    @review = review
    attributes ||= default_attributes
    super(attributes)
  end

  def to_model
    review
  end

  def create
    return if invalid?

    ActiveRecord::Base.transaction do
      @review_food = _review_food
      review = Review.create!(user_id: user_id, shop_food: @review_food,
                              content: content, title: title,
                              rate: rate, picture: picture)

      @review_food.calc_and_save_rate
      @review_id = review.id
    end
  rescue ActiveRecord::RecordInvalid => e
    p e
    false
  end

  def update
    return if invalid?

    ActiveRecord::Base.transaction do
      @review_food = _review_food
      review.update(user_id: user_id, shop_food: @review_food,
                    content: content, title: title,
                    rate: rate, picture: picture)
      @review_food.calc_and_save_rate
    end
  rescue ActiveRecord::RecordInvalid
    p e
    false
  end

  private

  attr_reader :review
  attr_accessor :review_food

  def default_attributes
    {
      review_id: review.id,
      user_id: review.user_id,
      food_id: review.shop_food_id ? review.shop_food.food_id : nil,
      content: review.content,
      title: review.title,
      shop_id: review.shop_food_id ? review.shop_food.shop_id : nil,
      rate: review.rate,
      picture: review.picture
    }
  end

  # 主キーに合致するShopFoodがあればそれを返す。なければ作成する。
  def _review_food
    shop = find_or_create_shop(shop_id)
    food = Food.find(food_id)
    ShopFood.find_by(food: food, shop: shop) || ShopFood.create!(food: food, shop: shop)
  end

  # 引数のidに該当するレコードがShop存在する場合はそれを返す。なければ作成する。
  def find_or_create_shop(id)
    shop = Shop.find_by_id(id)
    return shop unless shop.nil?

    # shopが見つからない場合、APIより情報を取得し登録する。
    shop_info = search_shop_by_id(id)['shop'][0]
    Shop.create!(id: id, large_area: shop_info['large_area']['name'], middle_area: shop_info['middle_area']['name'])
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  before_action :logged_in_user, only: %i[new create destroy edit update]
  before_action :correct_user, only: %i[destroy edit update]

  def new
    @form = ReviewForm.new
  end

  def create
    @form = ReviewForm.new(reviews_params)
    if @form.create
      flash[:success] = 'レビューを投稿しました'
      redirect_to current_user
    else
      render 'new'
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def edit
    @review = Review.find(params[:id])
    @form = ReviewForm.new(review: @review)
  end

  def update
    @review = Review.find(params[:id])
    @form = ReviewForm.new(reviews_params, review: @review)
    if @form.update
      flash[:success] = 'レビューを更新しました'
      redirect_to @review.user
    else
      render 'edit'
    end
  end

  def destroy
    review = Review.find(params[:id])
    shop_food = review.shop_food
    review.destroy
    shop_food.reviews.count.zero? ? shop_food.destroy : shop_food.calc_and_save_rate
    flash[:success] = 'レビューを削除しました'
    redirect_to user_path(@review_user)
  end

  private

  def reviews_params
    params.require(:review).permit(:content, :food_id, :title, :shop_id,
                                   :rate, :user_id, :category, :picture, :picture_cache)
  end

  def correct_user
    @review_user = Review.find(params[:id]).user
    redirect_to(review_path(params[:id])) unless current_user?(@review_user)
  end
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/views/reviews/_review.html.erb
<li>
  <div class="border-4 rounded-2xl w-11/12 mx-auto mb-4">
    <div class="border-b mx-auto p-2 flex flex-row">
      <div class="w-16 mx-3 my-auto">
        <% pic = review.user.picture? ? review.user.picture_url(:thumb) : "no_image.jpg" %>
        <%= image_tag pic, class: "rounded-full" %>
      </div>
      <div class="w-full my-auto">
        <div>
          投稿者：<%= link_to review.user.name, review.user, class: "link" %>
        </div>
        <div class="w-full sm:flex sm:justify-between">
          <div>
            <% created_at = review.created_at.strftime("%Y/%-m/%-d") %>
            <% updated_at = review.updated_at.strftime("%Y/%-m/%-d") %>
            <div><%= "投稿日：#{created_at}" %></div>
            <% if created_at != updated_at %>
              <div class="text-sm text-gray-500"><%= "(最終更新：#{updated_at})" %></div>
            <% end %>
          </div>
          <div class="mt-auto">
            <% if current_user?(review.user) %>
              <%= link_to "レビュー修正", edit_review_path(review), class: "link" %>
              <%= link_to "削除", review_path(review), method: :delete,
                            data: {confirm_swal: "本当に投稿を削除してよろしいですか？"},
                            class: "link mx-3" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% if @shop_food_disp %>
      <div class="border-b p-2 flex flex-row">
        <div class="w-16 mx-3 my-auto">
          <%= image_tag @shops[review.shop.id]['photo']['mobile']['l'] %>
        </div>
        <div class="w-full my-auto">
          <div>
            お店：<%= @shops[review.shop.id]['name'] %>
          </div>
          <div>
            料理：<%= link_to review.food.name, review.shop_food, class: "link" %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="m-1 bg-white md:flex md:flex-row-reverse">
      <div class="md:w-full">
        <div class="m-3">
          <span class="border-b-4 border-yellow-300 border-opacity-50 text-xl md:text-2xl font-semibold"><%= review.title %></span>
        </div>
        <div class="m-3">
          <div class="flex flex-row">
            <div class="flex flex-row star-rating" data-rate="<%= review.rate %>"></div>
            <div class="ml-2 font-semibold"><%= review.rate %></div>
          </div>
        </div>
        <div class="hidden md:block md:m-2">
          <%= simple_format(review.content) %>
        </div>
      </div>
      <% if review.picture? %>
        <div class="m-3">
          <div class="max-w-sm mx-auto">
            <%= image_tag review.picture_url, class: "object-contain max-h-80 mx-auto" %>
          </div>
          <% # ポートフォリオ用に収集したReview用画像のCC表記用 #60 %>
          <div id="cc-wrap" class="text-2xs text-gray-400 text-center"><%= review.picture_cc.html_safe if review.picture_cc? && review.picture.identifier.include?("cc_picture_") %></div>
        </div>
      <% end %>
    </div>
    <div class="m-3 text-sm md:hidden">
      <%= simple_format(review.content) %>
    </div>
    <div class="m-2 mt-6 text-xs md:text-sm md:flex md:flex-row-reverse">
      <div class="text-right md:py-1 md:ml-2">
        <%= render 'likes/count', review: review %>
      </div>
      <div class="text-right xsm:mr-2">
        <%= render 'likes/like_form', review: review if logged_in? %>
      </div>
    </div>
  </div>
</li>

app/views/reviews/_review_form.html.erb
<% @form.user_id ||= current_user.id %>
<%= form_with(model: @form, local:true) do |f| %>
<div class='mb-4'>
  <%= render 'shared/error_messages', object: f.object %>
</div>
<div class="mb-4 text-center">
  <span class="border-b-4 border-yellow-200 border-opacity-50"><%= yield(:description) %></span>
</div>
<div class="mx-5">
  <div class="lg:flex lg:flex-row-reverse">
    <div class="lg:w-8/12 lg:mx-auto">
      <%= f.hidden_field :user_id %>
      <div class="mb-4">
        <span class="label"><%= f.label :title, "タイトル", class: "block mb-2" %></span>
        <%= f.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>
      <div class="mb-4">
        <span class="label"><%= f.label :rate, "評価", class: "block mb-2" %></span>
        <div class="xsm:flex xsm:flex-row">
          <div class="flex flex-row" id="review-star-rating" data-rate="<%= @form.rate %>"></div>
          <div class="xsm:ml-4" id="hint1"></div>
        </div>
      </div>
      <div class="mb-4">
        <span class="label"><%= f.label :food_id, "料理", class: "block mb-2",id: "food-id-label", data: { food_id: @form.food_id } %></span>
        <div id="food-ddl"></div>
      </div>
      <div class="mb-4">
        <span class="label"><%= f.label :shop_id, "お店", class: "block mb-2", id: "shop-label", data: { shop_id: @form.shop_id } %></span>
        <div id="select-shop-modal"></div>
      </div>
      <div class="mb-4">
        <span class="label"><%= f.label :content, "内容", class: "block mb-2" %></span>
        <%= f.text_area :content, class: "h-48 shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>
    </div>
    <div class="mb-12 mx-auto lg:w-3/12 lg:my-auto">
      <div class="mb-4 mx-auto h-40 sm:h-60 lg:h-72" >
        <% pic = @form.picture? ? @form.picture_url : "no_image.jpg" %>
        <%= image_tag pic, id: "pic_preview", class: "h-full object-contain mx-auto" %>
      </div>
      <div class="w-7/12 mx-auto">
        <%= f.label :picture, '<i class="fa fa-folder-open mr-2" aria-hidden="true"></i>ファイル選択'.html_safe, class: "select-button block", for: "pic_field" %>
        <%= f.file_field :picture, id: "pic_field", class: "hidden" %>
        <%= f.hidden_field :picture_cache %>
      </div>
    </div>
  </div>
  <%= f.button yield(:submit_text), type: "button", class: "w-full text-center rounded py-2 bg-blue-400 hover:bg-blue-600 text-white", onclick: "submit();" %>
  <% end %>
  <%= stylesheet_pack_tag 'review_form' %>
  <%= javascript_pack_tag 'review_form' %>
  <%= javascript_pack_tag 'picture/preview' %>
  <!-- 評価javascript -->
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      $('#review-star-rating').raty({
        starOff: '<%= asset_path("star-off.png") %>',
        starOn: '<%= asset_path("star-on.png") %>',
        scoreName: 'review[rate]',
        target: '#hint1',
        targetText: '評価を選択してください',
        hints: ['とても悪い', '悪い', '普通', '良い', 'とても良い'],
        targetKeep: true,
        half: false,
        score: function() {
          return $(this).attr('data-rate');
        },
      });
    })
  </script>

app/views/reviews/edit.html.erb
<% provide(:title, "レビュー修正") %>
<% provide(:submit_text, "修正する") %>
<% provide(:description, "変更箇所を編集し、修正してください") %>
<div class="container mx-auto my-8">
  <%= render 'review_form' %>
</div>

app/views/reviews/new.html.erb
<% provide(:title, "レビュー投稿") %>
<% provide(:submit_text, "新規投稿") %>
<% provide(:description, "必要事項を入力し、投稿してください") %>
<div class="container mx-auto my-4">
  <%= render 'review_form' %>
</div>

app/views/reviews/show.html.erb
<% provide(:title, "レビュー詳細") %>
<div class="">
  <%= @review.shop_food.food.name %>,
  <%= @review.content %>,
  <%= link_to @review.user.name, @review.user %>,
  <%= time_ago_in_words(@review.updated_at) %>
  <% if @review.picture? %>
    <%= image_tag @review.picture.url %>
    <% # ポートフォリオ用に収集したReview用画像のCC表記用 #60 %>
    <%= @review.picture_cc.html_safe if @review.picture_cc? && @review.picture.identifier.include?("cc_picture_") %>
  <% end %>
</div>

<% if current_user?(@review.user) %>
  <div class="">
    <%= link_to "レビュー修正", edit_review_path(@review) %>
    <%= link_to "削除", review_path(@review), method: :delete,
                  data: {confirm: "本当に投稿を削除してよろしいですか？"} %>
  </div>
<% end%>