config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  get  'help',  to: 'static_pages#help'
  get  'about', to: 'static_pages#about'
  get  'shops', to: 'static_pages#shops'
  get  'signup', to: 'users#new'
  get  'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users
  resources :reviews, only: %i[new edit create update destroy show]
  resources :shop_foods, only: %i[index show]
  resources :likes, only: %i[create destroy]
  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :shops, only: %i[index show]
      resources :foods, only: %i[index]
      resources :areas, only: %i[index]
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="w-full h-16 flex items-center justify-center bg-gray-200">
  <div class="">
    © 2021 Ryohei Makabe
  </div>
</footer>

app/views/layouts/_header.html.erb
<div id="header" class="">
  <div class="md:flex">
    <div class="flex justify-start items-center w-full left-0 h-16 px-2 bg-gray-100">
      <%= link_to image_tag("title_logo.png"), "/", {class: "w-32 hover:opacity-50"} %>
      <% if logged_in? %>
        <%= link_to(current_user, class: "ml-auto header-link") do %>
            <div class="header-link-text">マイページ</div>
            <i class="fa fa-user fa-2x header-link-icon" aria-hidden="true"></i>
        <% end %>
        <%= link_to(logout_path, {method: :delete, class: "header-link"}) do %>
            <div class="header-link-text">ログアウト</div>
            <i class="fa fa-sign-out-alt fa-2x header-link-icon" aria-hidden="true"></i>
        <% end %>
      <% else %>
        <%= link_to(signup_path, class: "ml-auto header-link") do %>
            <div class="header-link-text">新規登録</div>
            <i class="fa fa-user-plus fa-2x header-link-icon" aria-hidden="true"></i>
        <% end %>
        <%= link_to(login_path, class: "header-link") do %>
            <div class="header-link-text">ログイン</div>
            <i class="fa fa-sign-in-alt fa-2x header-link-icon" aria-hidden="true"></i>
        <% end %>
      <% end %>
      <button @click="isOpen = !isOpen" class="xsm:mr-5 hover:opacity-50 focus:outline-none md:hidden text-center md:mx-5">
        <div class="text-3xs xsm:text-xs">メニュー</div>
        <span v-show="!isOpen">
          <i class="fa fa-bars fa-2x text-green-800" aria-hidden="true"></i>
        </span>
        <span v-show="isOpen">
          <i class="fa fa-times fa-2x text-green-800" aria-hidden="true"></i>
        </span>
      </button>
    </div>

  </div>
  <div id="sub-menu" :class="isOpen ? 'block' : 'hidden'" class="hidden absolute w-full bg-yellow-200 md:block md:static md:h-12 md:bg-gradient-to-b md:from-yellow-400 md:to-yellow-200 z-30">
    <ul class="md:flex md:justify-start md:items-center">
      <li class="border-b md:border-none">
        <%= link_to(help_path, class: "header-nav-link") do %>
          <i class="fa fa-info" aria-hidden="true"></i>
          ヘルプ
        <% end %>
      </li>
      <li class="border-b md:border-none">
        <%= link_to(shop_foods_path, class: "header-nav-link") do %>
          <i class="fa fa-search" aria-hidden="true"></i>
          料理別お店検索
        <% end %>
      </li>
      <li class="border-b md:border-none">
        <%= link_to(shops_path, class: "header-nav-link") do %>
          <i class="fa fa-search" aria-hidden="true"></i>
          お店検索
        <% end %>
      </li>
      <% if logged_in? %>
        <li class="border-b md:border-none">
          <%= link_to(edit_user_path(current_user), class: "header-nav-link") do %>
            <i class="fa fa-user-edit" aria-hidden="true"></i>
            登録情報更新
          <% end %>
        </li>
        <li class="border-b md:border-none">
          <%= link_to(new_review_path, class: "header-nav-link") do %>
            <i class="fa fa-plus" aria-hidden="true"></i>
            新規投稿
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<script>
  $(document).on('DOMContentLoaded', function() {
    document.getElementById('sub-menu').classList.remove('hidden')
    const header = new Vue({
      el: '#header',
      data: {
        isOpen: false,
      }
    });
  });
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>


    <%= render 'layouts/shim' %>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <!-- <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet"> -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body class="text-gray-700">
    <% if Rails.env.development? %>
      <div class="fixed top-0 right-0 m-8 p-3 text-xs font-mono text-white h-6 w-6 rounded-full flex items-center justify-center bg-gray-600 xsm:bg-gray-900 sm:bg-pink-500 md:bg-orange-500 lg:bg-green-500 xl:bg-blue-500">
        <div class="block  xsm:hidden sm:hidden md:hidden lg:hidden xl:hidden">al</div>
        <div class="hidden xsm:block sm:hidden md:hidden lg:hidden xl:hidden">xsm</div>
        <div class="hidden sm:block  md:hidden lg:hidden xl:hidden">sm</div>
        <div class="hidden sm:hidden md:block  lg:hidden xl:hidden">md</div>
        <div class="hidden sm:hidden md:hidden lg:block  xl:hidden">lg</div>
        <div class="hidden sm:hidden md:hidden lg:hidden xl:block">xl</div>
      </div>
    <% end %>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <div class="">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> w-11/12 sm:8/12 mx-auto my-2"><%= message %></div>
      <% end %>
      <div class="">
        <%= yield %>
      </div>
    </div>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>